price = float(input("price="))
discount = float(input("discount="))
vat = float(input("vat="))
base = round(price*(1 - discount/100),2)
vat_amount = round(base*(vat/100),2)
total = round(base + vat_amount, 2)
print(f"База после скидки: {base:.2f}","₽")
print(f"НДС:               {vat_amount:.2f}","₽")
print(f"Итого к оплате:    {total:.2f}","₽")